#ifndef CRANKLE_VERSION_H
#define CRANKLE_VERSION_H

#define CRANKLE_VERSION_MAJOR 0
#define CRANKLE_VERSION_MINOR 2
#define CRANKLE_VERSION_PATCH 2
#define CRANKLE_VERSION_STRING "0.2.2"

#endif
