#ifndef CRANKLE_VERSION_H
#define CRANKLE_VERSION_H

#define CRANKLE_VERSION_MAJOR 0
#define CRANKLE_VERSION_MINOR 3
#define CRANKLE_VERSION_PATCH 0
#define CRANKLE_VERSION_STRING "0.3.0-alpha"

#endif
